# Generated by Django 3.1.4 on 2020-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
